- name: Common Dev Environment
  hosts: localhost
  vars_files:
    - vars/main.yml
    - vars/repo.yml
  roles:
    - role: autonomous
      tags: autonomous
    - role: electrons
      tags: electrons