---
- name: Include vars
  ansible.builtin.include_vars: main.yml
  ansible.builtin.include_vars: repo.yml

- name: Include OS and arch specific tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}-{{ ansible_machine }}.yml"